export interface Herb {
  id: string
  name: string
  latinName: string
  category: string
  origin: string
  description: string
  benefits: string[]
  preparation: string[]
  drSebiNote?: string
  usedIn?: string[]
  accent: string
}

export const herbs: Herb[] = [
  {
    id: 'sea-moss',
    name: 'Sea Moss',
    latinName: 'Chondrus Crispus',
    category: 'Sea Vegetable',
    origin: 'Atlantic coastlines — Ireland, Jamaica, Caribbean',
    description: 'One of the most mineral-dense plants on earth. Wild-crafted Sea Moss contains 92 of the 102 minerals the human body requires. It builds the body from the inside out — feeding the thyroid, gut, skin, and immune system simultaneously.',
    benefits: ['Thyroid & hormone support', 'Gut healing & digestion', 'Skin clarity & collagen', 'Immune strengthening', 'Cellular hydration & mineralization'],
    preparation: ['Gel blended with spring water', 'Added to smoothies & juices', 'Capsule form', 'Topical face mask'],
    drSebiNote: 'Dr. Sebi called sea moss one of the most complete foods available to the human body. He praised its bio-mineral content and used it as a foundation in many of his compounds.',
    usedIn: ['Chondrus Crispus Sea Moss Gel'],
    accent: '#1a6b3c',
  },
  {
    id: 'bladderwrack',
    name: 'Bladderwrack',
    latinName: 'Fucus vesiculosus',
    category: 'Sea Vegetable',
    origin: 'North Atlantic & Pacific Oceans',
    description: 'A mineral-rich brown algae most recognized for its iodine content. Frequently paired with sea moss to create a complete thyroid and metabolic support blend. Contains fucoidan — a sulfated polysaccharide studied for its powerful cellular effects.',
    benefits: ['Thyroid regulation & iodine source', 'Metabolism support', 'Anti-inflammatory', 'Digestive health', 'Weight management support'],
    preparation: ['Capsules', 'Combined with sea moss gel', 'Tea', 'Powder in smoothies'],
    drSebiNote: 'Often combined with sea moss and burdock root as a mineral trinity for the endocrine system.',
    usedIn: ['Essential 1 Daily Minerals'],
    accent: '#2d6b4e',
  },
  {
    id: 'burdock-root',
    name: 'Burdock Root',
    latinName: 'Arctium lappa',
    category: 'Root',
    origin: 'Europe, Asia, North America',
    description: 'A cornerstone blood and lymphatic purifier. Burdock root draws toxins from the blood into the lymphatic system for elimination, while simultaneously supporting the liver and kidneys. One of the deepest cleansing herbs available.',
    benefits: ['Blood & lymphatic purification', 'Liver & kidney support', 'Skin health (eczema, acne, psoriasis)', 'Lymphatic drainage', 'Anti-diabetic & blood sugar regulation'],
    preparation: ['Tea from dried root', 'Tincture', 'Capsules', 'Decoction (boiled root)', 'Eaten as a vegetable (gobo)'],
    drSebiNote: 'A cornerstone of Dr. Sebi\'s methodology. He used burdock root extensively for blood and lymphatic cleansing, calling it essential for full-body detoxification before any other herbs could be effective.',
    accent: '#8b5e3c',
  },
  {
    id: 'sarsaparilla',
    name: 'Sarsaparilla',
    latinName: 'Smilax regelii',
    category: 'Root',
    origin: 'Central America, Jamaica, South America',
    description: 'A powerful blood purifier and hormone balancer native to the tropics. Its saponins bind to endotoxins in the gut and carry them out of the body. Historically used for skin conditions and hormonal imbalance across indigenous cultures.',
    benefits: ['Hormone balance (testosterone & estrogen)', 'Blood stream cleansing', 'Skin conditions (psoriasis, eczema, rosacea)', 'Liver detoxification', 'Anti-inflammatory & joint support'],
    preparation: ['Tea', 'Tincture', 'Capsules', 'Decoction'],
    drSebiNote: 'Dr. Sebi highlighted sarsaparilla as irreplaceable for treating skin diseases at their root — in the blood. He considered it one of the finest herbs for removing systemic toxins.',
    accent: '#7a3d2a',
  },
  {
    id: 'moringa',
    name: 'Moringa',
    latinName: 'Moringa oleifera',
    category: 'Leaf',
    origin: 'Sub-Himalayan India, Pakistan, sub-Saharan Africa',
    description: 'Called the "Miracle Tree." Moringa leaves contain more vitamin C than oranges, more calcium than milk, more iron than spinach, and more potassium than bananas — all in an alkaline-friendly, bioavailable form. One of the most complete plant foods known.',
    benefits: ['Energy & sustained vitality', 'Anti-inflammatory (comparable to NSAIDs)', 'Blood sugar regulation', 'Complete amino acid profile', 'Bone, muscle & nerve health'],
    preparation: ['Powder in smoothies & water', 'Tea from dried leaves', 'Capsules', 'Fresh leaves cooked or raw'],
    accent: '#4a7c59',
  },
  {
    id: 'elderberry',
    name: 'Elderberry',
    latinName: 'Sambucus nigra',
    category: 'Berry',
    origin: 'Europe, North America, North Africa',
    description: 'One of the most widely studied immune herbs in the world. Rich in anthocyanins — plant pigments that protect cells from oxidative stress. Used across European and Indigenous healing traditions for centuries to prevent and shorten illness.',
    benefits: ['Immune system activation', 'Cold & flu prevention & recovery', 'Antiviral properties', 'Antioxidant-rich cellular protection', 'Sinus & respiratory support'],
    preparation: ['Syrup', 'Capsules', 'Gummies', 'Tea', 'Tincture'],
    accent: '#5a1a7a',
  },
  {
    id: 'soursop',
    name: 'Soursop',
    latinName: 'Annona muricata',
    category: 'Fruit',
    origin: 'Caribbean, Central America, South America',
    description: 'Also known as Guanabana. Both the creamy fruit and the leaves carry distinct healing properties. The leaves contain acetogenins — compounds of intense scientific interest for their cellular-level effects. One of the most celebrated healing fruits in the Caribbean.',
    benefits: ['Cellular health & immunity', 'Anti-inflammatory', 'Digestive support & gut motility', 'Blood pressure regulation', 'Mood support & anti-anxiety'],
    preparation: ['Leaf tea', 'Fresh fruit eaten raw', 'Fruit juice', 'Leaf capsules'],
    drSebiNote: 'Highly regarded in Dr. Sebi\'s compound formulas for supporting cellular regeneration and immune function at depth.',
    accent: '#5a7a2a',
  },
  {
    id: 'dandelion-root',
    name: 'Dandelion Root',
    latinName: 'Taraxacum officinale',
    category: 'Root',
    origin: 'Europe, Asia (naturalized globally)',
    description: 'One of the most effective liver herbs available. The roasted root acts as a bitter digestive that stimulates bile production, improves fat digestion, and feeds the beneficial bacteria that line the gut. Every part of the dandelion is food and medicine.',
    benefits: ['Liver detox & bile production', 'Digestive health & enzyme activation', 'Diuretic & kidney cleanse', 'Blood sugar stabilization', 'Iron, vitamins A, C & K source'],
    preparation: ['Tea from roasted or raw root', 'Tincture', 'Capsules', 'Fresh leaves in salads', 'Dandelion coffee (roasted root)'],
    accent: '#c4a100',
  },
  {
    id: 'nettle',
    name: 'Nettle Leaf',
    latinName: 'Urtica dioica',
    category: 'Leaf',
    origin: 'Europe, Asia, North America',
    description: 'Pound for pound, one of the most mineral-rich plants available. Nettle provides iron, calcium, magnesium, potassium, and silicon — making it essential for rebuilding mineral deficiencies that arise during alkaline transitions and detox protocols.',
    benefits: ['Iron & mineral replenishment', 'Seasonal allergy & hayfever relief', 'Joint & arthritis support', 'Kidney & urinary tract health', 'Hair growth & nail strength'],
    preparation: ['Tea', 'Tincture', 'Capsules', 'Cooked as greens', 'Freeze-dried powder'],
    accent: '#2d6b3c',
  },
  {
    id: 'blue-vervain',
    name: 'Blue Vervain',
    latinName: 'Verbena hastata',
    category: 'Flower',
    origin: 'North America, Caribbean',
    description: 'A powerful nervine herb for those who carry stress physically in the body — especially in the neck, shoulders, jaw, or chest. Blue vervain calms an overactive nervous system, drains stress from the lymphatic tissue, and brings the body back to rest.',
    benefits: ['Nervous system calming', 'Stress & anxiety embodied in the body', 'Lymphatic clearing', 'Liver support & fever reduction', 'Muscle tension & headache relief'],
    preparation: ['Tea', 'Tincture (bitter — add honey)', 'Capsules'],
    drSebiNote: 'Used in Dr. Sebi\'s nervous system protocols. He recommended blue vervain for clearing accumulated stress held in the lymphatic tissue and for people who struggle to fully relax.',
    accent: '#4a3a8b',
  },
  {
    id: 'chaparral',
    name: 'Chaparral',
    latinName: 'Larrea tridentata',
    category: 'Leaf',
    origin: 'Mojave & Sonoran Deserts, Northern Mexico',
    description: 'A desert medicine used by Indigenous peoples of the American Southwest for thousands of years. Contains NDGA — nordihydroguaiaretic acid — one of the most potent natural antioxidants and free-radical scavengers identified by modern research.',
    benefits: ['Powerful systemic antioxidant', 'Blood purification', 'Skin conditions (acne, psoriasis, eczema)', 'Anti-parasitic & anti-microbial', 'Liver protection'],
    preparation: ['Tea (small amounts — strong herb)', 'Tincture', 'Topical poultice', 'Capsules'],
    drSebiNote: 'One of Dr. Sebi\'s strongest blood-cleansing herbs. He used chaparral in compounds designed for deep cellular cleaning and as a primary tool for addressing chronic skin disease at its root.',
    accent: '#8b6b2a',
  },
  {
    id: 'nopal',
    name: 'Nopal (Prickly Pear)',
    latinName: 'Opuntia ficus-indica',
    category: 'Plant',
    origin: 'Mexico, Central America',
    description: 'A dual-purpose alkaline food and medicine. The cactus pads are rich in fiber, minerals, and mucilaginous compounds that coat, soothe, and heal the digestive lining. One of the handful of foods explicitly approved in Dr. Sebi\'s nutritional guide.',
    benefits: ['Blood sugar regulation & insulin sensitivity', 'Digestive lining healing', 'Anti-inflammatory', 'Cholesterol reduction', 'Antioxidant-rich cellular support'],
    preparation: ['Fresh pads (nopales) cooked in meals', 'Juice', 'Capsules', 'Powder in smoothies'],
    drSebiNote: 'An alkaline-approved food and medicine in Dr. Sebi\'s nutritional guide. He recommended nopal as a staple for managing blood sugar and supporting the digestive system.',
    accent: '#6b8b2a',
  },
  {
    id: 'cascara-sagrada',
    name: 'Cascara Sagrada',
    latinName: 'Rhamnus purshiana',
    category: 'Bark',
    origin: 'Pacific Northwest — Oregon, Washington, British Columbia',
    description: 'Literally "Sacred Bark." A reliable, non-habit-forming colon tonic used for centuries. Cascara stimulates the peristaltic wave — the muscular contractions that move waste through the bowel — while simultaneously toning and strengthening the colon walls.',
    benefits: ['Colon cleansing & regularity', 'Constipation relief (non-habit-forming)', 'Intestinal toning & strength', 'Liver & gallbladder support', 'Digestive bitters activation'],
    preparation: ['Tea from aged bark', 'Capsules', 'Tincture'],
    accent: '#8b5a2a',
  },
  {
    id: 'yellow-dock',
    name: 'Yellow Dock',
    latinName: 'Rumex crispus',
    category: 'Root',
    origin: 'Europe, Western Asia (naturalized globally)',
    description: 'The iron herb. Yellow dock root contains bioavailable iron and simultaneously stimulates bile production for better iron absorption — making it far more effective than synthetic supplements. Essential for alkaline protocols addressing iron-deficiency anemia.',
    benefits: ['Iron building & blood health', 'Liver & bile stimulation', 'Skin conditions rooted in blood toxicity', 'Lymphatic support', 'Digestive health'],
    preparation: ['Tea', 'Tincture', 'Capsules', 'Decoction'],
    drSebiNote: 'Frequently used in Dr. Sebi\'s iron compounds alongside burdock root and nettle — addressing anemia through whole-plant bioavailability rather than toxic synthetic supplementation.',
    accent: '#c4b820',
  },
  {
    id: 'black-seed',
    name: 'Black Seed',
    latinName: 'Nigella sativa',
    category: 'Seed',
    origin: 'Southwest Asia, Mediterranean, North Africa',
    description: 'Known in Islamic tradition as "the cure for everything except death." Contains thymoquinone — one of the most extensively studied natural anti-inflammatory and antioxidant compounds in modern science. Effective across a wide range of body systems.',
    benefits: ['Immune system fortification', 'Anti-inflammatory (whole body)', 'Respiratory health & asthma', 'Blood pressure regulation', 'Gut health & anti-parasitic'],
    preparation: ['Cold-pressed oil (teaspoon daily)', 'Whole seeds added to food', 'Capsules', 'Ground into paste with honey'],
    accent: '#2a2a4a',
  },
  {
    id: 'valerian-root',
    name: 'Valerian Root',
    latinName: 'Valeriana officinalis',
    category: 'Root',
    origin: 'Europe and Asia',
    description: 'Nature\'s sleep medicine. Valerian root increases GABA activity in the brain — the same neurotransmitter targeted by pharmaceutical sleep and anxiety medications — but gently, without addiction, dependency, or morning grogginess.',
    benefits: ['Deep, restful sleep support', 'Anxiety & nervous tension relief', 'Muscle relaxation & tension headaches', 'Menstrual cramp relief', 'Blood pressure calming'],
    preparation: ['Tea (unpleasant taste — blend with mint)', 'Capsules (most common)', 'Tincture', 'Extract powder'],
    accent: '#6b3a8b',
  },
  {
    id: 'tila',
    name: 'Tila (Linden Flower)',
    latinName: 'Tilia europaea',
    category: 'Flower',
    origin: 'Europe, North Africa, Western Asia',
    description: 'A gently fragrant flower used across European, African, and Latin American healing traditions for calming, heart health, and fever relief. One of the most approachable herbs for daily stress and sleep support. Beloved across cultures for its safety and effectiveness.',
    benefits: ['Nervous system calming (gentle, daily use)', 'Heart & cardiovascular tonifying', 'Cold, flu & fever relief (with sweat)', 'Digestive settling & gut calming', 'Anxiety & mild insomnia support'],
    preparation: ['Tea from flowers (delicious)', 'Tincture', 'Steam inhalation', 'Capsules'],
    accent: '#90b840',
  },
  {
    id: 'fennel-seed',
    name: 'Fennel Seed',
    latinName: 'Foeniculum vulgare',
    category: 'Seed',
    origin: 'Mediterranean',
    description: 'A classic digestive herb with a natural sweetness. Fennel relaxes the smooth muscles of the gastrointestinal tract, relieving gas, bloating, and cramps within minutes. Safe enough for nursing infants with colic, powerful enough for adult IBS.',
    benefits: ['Gas, bloating & digestive cramping', 'IBS & spastic colon relief', 'Natural estrogen balance', 'Nursing milk production support', 'Oral health & breath freshening'],
    preparation: ['Chewed whole after meals', 'Tea', 'Tincture', 'Essential oil (well diluted)'],
    accent: '#5a8a3a',
  },
]

export const herbCategories = ['All', 'Sea Vegetable', 'Root', 'Leaf', 'Flower', 'Berry', 'Fruit', 'Seed', 'Bark', 'Plant']

export const healthBenefits = [
  'All',
  'Immune Support',
  'Digestive Health',
  'Blood & Circulation',
  'Energy & Vitality',
  'Sleep & Calm',
  'Skin & Hair',
  'Thyroid Support',
  'Detox & Cleanse',
]

export const benefitKeywords: Record<string, string[]> = {
  'Immune Support':    ['immune', 'antiviral', 'cellular', 'cold', 'flu', 'respiratory'],
  'Digestive Health':  ['digest', 'gut', 'colon', 'intestin', 'bloat', 'bile', 'bowel', 'cramp', 'ibs'],
  'Blood & Circulation': ['blood', 'iron', 'anemia', 'circulation', 'pressure', 'cholesterol'],
  'Energy & Vitality': ['energy', 'vitalit', 'fatigue', 'stamina', 'mineral', 'amino'],
  'Sleep & Calm':      ['sleep', 'calm', 'anxiety', 'nervous', 'stress', 'relax', 'tension', 'insomnia'],
  'Skin & Hair':       ['skin', 'hair', 'acne', 'eczema', 'psoriasis', 'nail', 'collagen'],
  'Thyroid Support':   ['thyroid', 'hormone', 'iodine', 'metabolis', 'endocrine'],
  'Detox & Cleanse':   ['detox', 'cleanse', 'purif', 'liver', 'lymphat', 'toxin', 'kidney'],
}
